function [eye2]=eyecomanalyze(inputdata,sample_rate,spb,PAM_order)
h = commscope.eyediagram('SamplingFrequency', sample_rate, ...
                         'SamplesPerSymbol', spb, ...
                         'SymbolsPerTrace', 2, ...
                         'MinimumAmplitude', -PAM_order, ...
                         'MaximumAmplitude', PAM_order, ...
                         'AmplitudeResolution', 0.0100, ...
                         'MeasurementDelay', 0, ...
                         'PlotType', '2D Color', ...
                         'PlotTimeOffset', 0, ...
                         'PlotPDFRange', [0 1], ...
                         'ColorScale', 'linear', ...
                         'RefreshPlot', 'off');
% h.MeasurementSetup.EyeLevelBoundary=[50 50];
update(h,inputdata);
analyze(h);

eye2.SNR=10*log10(((h.Measurements.EyeSNR).^2));
eye2.amp=h.Measurements.EyeAmplitude;
eye2.height=h.Measurements.EyeHeight;
eye2.width=h.Measurements.EyeWidth;
eye2.vopen=h.Measurements.EyeOpeningVertical;
eye2.hopen=h.Measurements.EyeOpeningHorizontal;
eye2.risetime=h.Measurements.RiseTime;

h2 = commscope.eyediagram('SamplingFrequency', sample_rate, ...
                         'SamplesPerSymbol', spb, ...
                         'SymbolsPerTrace', 2, ...
                         'MinimumAmplitude', -PAM_order, ...
                         'MaximumAmplitude', PAM_order, ...
                         'AmplitudeResolution', 0.0100, ...
                         'MeasurementDelay', 0, ...
                         'PlotType', '2D Color', ...
                         'PlotTimeOffset', 0, ...
                         'PlotPDFRange', [0 1], ...
                         'ColorScale', 'linear', ...
                         'RefreshPlot', 'off');
% h2.MeasurementSetup.EyeLevelBoundary=[50 50];
h2.MeasurementSetup.BERThreshold=3.8e-3;
update(h2,inputdata);
analyze(h2);
eye2.vopenfec=h2.Measurements.EyeOpeningVertical;
eye2.hopenfec=h2.Measurements.EyeOpeningHorizontal;

% function varargout = checkClipping(this)
% function analyze(this, varargin)